server:
  port: 8000

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://flowchat.shop:30001/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      default-filters: # default-filter를 global filter으로 사용
        - name: GlobalFilter # class 이름
          args: # 위의 클래스에서 상속받은 AbstractGatewayFilterFactory의 제네릭에 표시된 클래스의 파라미터들
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service-sign-up
          uri: lb://MEMBER-SERVICE
          predicates: # 조건에 해당
            - Path=/member-service/sign-up # localhost:8000/swagger 요청에 해당하는 경우
            - Method=POST # 위의 요청이 GET으로 온 경우
          filters: # predicates에 해당하는 요청의 경우 아래의 필터를 처리하겠다는 뜻
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
#            - LoggingFilter
        - id: member-service-sign-in
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/sign-in
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: member-service-health-check
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/common/health-check
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
#            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter